apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_connections"
  DB_NAME: "connections"
  DB_HOST: "postgres-connections"
  DB_PORT: "5432"
  KAFKA_URL: location-kafka.default.svc.cluster.local
  KAFKA_TOPIC: test
metadata:
  name: location-producer-map
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer
  template:
    metadata:
      labels:
        service: location-producer
    spec:
      containers:
      - image: duarch/udaconnect-producer:latest
        name: location-producer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location-producer-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-producer-map
              key: KAFKA_TOPIC
      restartPolicy: Always
